-- =============================================================================
-- 2026-05-11 - Serasa PEFIN
-- Script idempotente para criar a base persistente da integracao Serasa PEFIN.
-- Nao executar diretamente em producao; aplicar de forma controlada em dev/UAT.
-- =============================================================================

IF OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SERASA_PEFIN_SOLICITACOES (
        ID uniqueidentifier NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_SOLICITACOES_ID DEFAULT (NEWID()),
        NUM_VENDA_FK int NOT NULL,
        TIPO_REGISTRO varchar(20) NOT NULL,
        ID_SOLICITACAO_PRINCIPAL uniqueidentifier NULL,
        ID_ASSOCIADO varchar(64) NULL,
        TIPO_ASSOCIACAO varchar(64) NULL,
        DOCUMENTO_DEVEDOR varchar(20) NOT NULL,
        DOCUMENTO_GARANTIDOR varchar(20) NULL,
        DOCUMENTO_CREDOR varchar(20) NOT NULL,
        CONTRACT_NUMBER varchar(20) NOT NULL,
        CATEGORY_ID char(2) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_SOLICITACOES_CATEGORY_ID DEFAULT ('FI'),
        AREA_INFORMANTE varchar(4) NOT NULL,
        VALOR decimal(15,2) NOT NULL,
        DATA_VENCIMENTO date NOT NULL,
        STATUS varchar(32) NOT NULL,
        TRANSACTION_ID varchar(64) NULL,
        CADUS_KEY varchar(64) NULL,
        CADUS_SERIE varchar(64) NULL,
        PAYLOAD_AUDITORIA nvarchar(max) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_SOLICITACOES_PAYLOAD_AUDITORIA DEFAULT (N'{}'),
        WEBHOOK_PAYLOAD nvarchar(max) NULL,
        ERROR_MESSAGE nvarchar(1000) NULL,
        ERROR_STATUS_CODE int NULL,
        OPERADOR varchar(255) NOT NULL,
        DT_CRIACAO datetime2(0) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_SOLICITACOES_DT_CRIACAO DEFAULT (SYSUTCDATETIME()),
        DT_ATUALIZACAO datetime2(0) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_SOLICITACOES_DT_ATUALIZACAO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SERASA_PEFIN_SOLICITACOES PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.SERASA_PEFIN_WEBHOOKS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SERASA_PEFIN_WEBHOOKS (
        ID uniqueidentifier NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_WEBHOOKS_ID DEFAULT (NEWID()),
        EVENT_TYPE varchar(64) NOT NULL,
        TRANSACTION_ID varchar(64) NULL,
        PAYLOAD nvarchar(max) NOT NULL,
        MATCHED_SOLICITACAO_ID uniqueidentifier NULL,
        PROCESSADO bit NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_WEBHOOKS_PROCESSADO DEFAULT (0),
        MENSAGEM_ERRO nvarchar(1000) NULL,
        DT_RECEBIMENTO datetime2(0) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_WEBHOOKS_DT_RECEBIMENTO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SERASA_PEFIN_WEBHOOKS PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_TIPO_REGISTRO', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_TIPO_REGISTRO
        CHECK (TIPO_REGISTRO IN ('PRINCIPAL', 'GARANTIDOR'));
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_STATUS', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_STATUS
        CHECK (STATUS IN (
            'PENDENTE_ENVIO',
            'ENVIADO_SERASA',
            'AGUARDANDO_RETORNO',
            'NEGATIVADO_SUCESSO',
            'NEGATIVADO_ERRO',
            'BAIXA_ENVIADA',
            'BAIXA_AGUARDANDO_RETORNO',
            'BAIXADO_SUCESSO',
            'BAIXADO_ERRO'
        ));
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_PAYLOAD_AUDITORIA_JSON', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_PAYLOAD_AUDITORIA_JSON
        CHECK (ISJSON(PAYLOAD_AUDITORIA) = 1);
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_WEBHOOK_PAYLOAD_JSON', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_WEBHOOK_PAYLOAD_JSON
        CHECK (WEBHOOK_PAYLOAD IS NULL OR ISJSON(WEBHOOK_PAYLOAD) = 1);
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_VALOR', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_VALOR
        CHECK (VALOR >= 0);
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_ERROR_STATUS_CODE', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_ERROR_STATUS_CODE
        CHECK (ERROR_STATUS_CODE IS NULL OR ERROR_STATUS_CODE BETWEEN 100 AND 599);
END
GO

IF OBJECT_ID('dbo.FK_SERASA_PEFIN_SOLICITACOES_PRINCIPAL', 'F') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT FK_SERASA_PEFIN_SOLICITACOES_PRINCIPAL
        FOREIGN KEY (ID_SOLICITACAO_PRINCIPAL)
        REFERENCES dbo.SERASA_PEFIN_SOLICITACOES (ID);
END
GO

IF OBJECT_ID('dbo.CK_SERASA_PEFIN_WEBHOOKS_PAYLOAD_JSON', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_WEBHOOKS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_WEBHOOKS_PAYLOAD_JSON
        CHECK (ISJSON(PAYLOAD) = 1);
END
GO

IF OBJECT_ID('dbo.FK_SERASA_PEFIN_WEBHOOKS_SOLICITACAO', 'F') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_WEBHOOKS WITH CHECK
    ADD CONSTRAINT FK_SERASA_PEFIN_WEBHOOKS_SOLICITACAO
        FOREIGN KEY (MATCHED_SOLICITACAO_ID)
        REFERENCES dbo.SERASA_PEFIN_SOLICITACOES (ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_SOLICITACOES_NUM_VENDA_FK'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_SOLICITACOES_NUM_VENDA_FK
        ON dbo.SERASA_PEFIN_SOLICITACOES (NUM_VENDA_FK, DT_CRIACAO DESC)
        INCLUDE (TIPO_REGISTRO, STATUS, CONTRACT_NUMBER, TRANSACTION_ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SERASA_PEFIN_SOLICITACOES_TRANSACTION_ID'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_SERASA_PEFIN_SOLICITACOES_TRANSACTION_ID
        ON dbo.SERASA_PEFIN_SOLICITACOES (TRANSACTION_ID)
        WHERE TRANSACTION_ID IS NOT NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_SOLICITACOES_CONTRACT_NUMBER'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_SOLICITACOES_CONTRACT_NUMBER
        ON dbo.SERASA_PEFIN_SOLICITACOES (CONTRACT_NUMBER, NUM_VENDA_FK)
        INCLUDE (TIPO_REGISTRO, STATUS, TRANSACTION_ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_SOLICITACOES_STATUS'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_SOLICITACOES_STATUS
        ON dbo.SERASA_PEFIN_SOLICITACOES (STATUS, DT_ATUALIZACAO DESC)
        INCLUDE (NUM_VENDA_FK, CONTRACT_NUMBER, TRANSACTION_ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SERASA_PEFIN_SOLICITACOES_ATIVA'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_SERASA_PEFIN_SOLICITACOES_ATIVA
        ON dbo.SERASA_PEFIN_SOLICITACOES (
            NUM_VENDA_FK,
            CONTRACT_NUMBER,
            DOCUMENTO_DEVEDOR,
            DOCUMENTO_GARANTIDOR,
            TIPO_REGISTRO
        )
        WHERE STATUS IN ('PENDENTE_ENVIO', 'ENVIADO_SERASA', 'AGUARDANDO_RETORNO');
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_WEBHOOKS_TRANSACTION_ID'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_WEBHOOKS')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_WEBHOOKS_TRANSACTION_ID
        ON dbo.SERASA_PEFIN_WEBHOOKS (TRANSACTION_ID, DT_RECEBIMENTO DESC)
        INCLUDE (EVENT_TYPE, PROCESSADO, MATCHED_SOLICITACAO_ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_WEBHOOKS_PROCESSADO'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_WEBHOOKS')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_WEBHOOKS_PROCESSADO
        ON dbo.SERASA_PEFIN_WEBHOOKS (PROCESSADO, DT_RECEBIMENTO DESC)
        INCLUDE (EVENT_TYPE, TRANSACTION_ID, MATCHED_SOLICITACAO_ID);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_WEBHOOKS_MATCHED_SOLICITACAO_ID'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_WEBHOOKS')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_WEBHOOKS_MATCHED_SOLICITACAO_ID
        ON dbo.SERASA_PEFIN_WEBHOOKS (MATCHED_SOLICITACAO_ID, DT_RECEBIMENTO DESC)
        WHERE MATCHED_SOLICITACAO_ID IS NOT NULL;
END
GO
