IF OBJECT_ID('dbo.SERASA_PEFIN_SOLICITACOES', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.CK_SERASA_PEFIN_SOLICITACOES_STATUS', 'C') IS NOT NULL
    BEGIN
        ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES
        DROP CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_STATUS;
    END

    ALTER TABLE dbo.SERASA_PEFIN_SOLICITACOES WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_SOLICITACOES_STATUS
        CHECK (STATUS IN (
            'PENDENTE_ENVIO',
            'ENVIADO_SERASA',
            'AGUARDANDO_RETORNO',
            'NEGATIVADO_SUCESSO',
            'NEGATIVADO_ERRO',
            'BAIXA_ENVIADA',
            'BAIXA_AGUARDANDO_RETORNO',
            'BAIXADO_SUCESSO',
            'BAIXADO_ERRO'
        ));
END
GO
