-- =============================================================================
-- 2026-06-03 - Serasa PEFIN: Tabela de Baixas (Write-Off)
-- Script idempotente para criar a tabela de solicitacoes de baixa, com FK para
-- SERASA_PEFIN_SOLICITACOES, CHECK constraints (motivo whitelist + status),
-- e indice unico filtrado para impedir baixa ativa duplicada por parcela.
-- Nao executar diretamente em producao; aplicar de forma controlada em dev/UAT.
-- Requer permissao ALTER TABLE (usar usuario dwbi).
-- =============================================================================

SET QUOTED_IDENTIFIER ON;
GO

-- 1) Tabela base
IF OBJECT_ID('dbo.SERASA_PEFIN_BAIXAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SERASA_PEFIN_BAIXAS (
        ID uniqueidentifier NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_BAIXAS_ID DEFAULT (NEWID()),
        ID_SOLICITACAO_NEGATIVACAO uniqueidentifier NOT NULL,
        NUM_VENDA_FK int NOT NULL,
        NUMERO_PARCELA int NULL,
        CONTRACT_NUMBER varchar(20) NOT NULL,
        DOCUMENTO_DEVEDOR varchar(20) NOT NULL,
        DOCUMENTO_CREDOR varchar(20) NOT NULL,
        MOTIVO tinyint NOT NULL,
        STATUS varchar(40) NOT NULL,
        SOLICITANTE_USERNAME varchar(100) NOT NULL,
        APROVADOR_USERNAME varchar(100) NULL,
        DT_APROVACAO datetime2(0) NULL,
        JUSTIFICATIVA nvarchar(500) NULL,
        TRANSACTION_ID varchar(64) NULL,
        WEBHOOK_PAYLOAD nvarchar(max) NULL,
        ERROR_MESSAGE nvarchar(1000) NULL,
        ERROR_STATUS_CODE int NULL,
        TENTATIVAS tinyint NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_BAIXAS_TENTATIVAS DEFAULT (1),
        DT_CRIACAO datetime2(0) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_BAIXAS_DT_CRIACAO DEFAULT (SYSUTCDATETIME()),
        DT_ATUALIZACAO datetime2(0) NOT NULL
            CONSTRAINT DF_SERASA_PEFIN_BAIXAS_DT_ATUALIZACAO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SERASA_PEFIN_BAIXAS PRIMARY KEY (ID)
    );
END
GO

-- 2) FK para SERASA_PEFIN_SOLICITACOES (negativacao de origem)
IF OBJECT_ID('dbo.FK_SERASA_PEFIN_BAIXAS_SOLICITACAO', 'F') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT FK_SERASA_PEFIN_BAIXAS_SOLICITACAO
        FOREIGN KEY (ID_SOLICITACAO_NEGATIVACAO)
        REFERENCES dbo.SERASA_PEFIN_SOLICITACOES (ID);
END
GO

-- 3) CHECK MOTIVO (whitelist Serasa: 01,02,03,04,19,43,45)
IF OBJECT_ID('dbo.CK_SERASA_PEFIN_BAIXAS_MOTIVO', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_BAIXAS_MOTIVO
        CHECK (MOTIVO IN (1, 2, 3, 4, 19, 43, 45));
END
GO

-- 4) CHECK STATUS (subset de estados relevantes para baixa)
IF OBJECT_ID('dbo.CK_SERASA_PEFIN_BAIXAS_STATUS', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_BAIXAS_STATUS
        CHECK (STATUS IN (
            'AGUARDANDO_APROVACAO',
            'APROVADA',
            'REJEITADA',
            'APROVADA_FALHA_ENVIO',
            'PENDENTE_ENVIO',
            'BAIXA_ENVIADA',
            'BAIXA_AGUARDANDO_RETORNO',
            'BAIXADO_SUCESSO',
            'BAIXADO_ERRO'
        ));
END
GO

-- 5) CHECK WEBHOOK_PAYLOAD precisa ser JSON valido quando nao null
IF OBJECT_ID('dbo.CK_SERASA_PEFIN_BAIXAS_WEBHOOK_PAYLOAD_JSON', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_BAIXAS_WEBHOOK_PAYLOAD_JSON
        CHECK (WEBHOOK_PAYLOAD IS NULL OR ISJSON(WEBHOOK_PAYLOAD) = 1);
END
GO

-- 6) CHECK ERROR_STATUS_CODE
IF OBJECT_ID('dbo.CK_SERASA_PEFIN_BAIXAS_ERROR_STATUS_CODE', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_BAIXAS_ERROR_STATUS_CODE
        CHECK (ERROR_STATUS_CODE IS NULL OR ERROR_STATUS_CODE BETWEEN 100 AND 599);
END
GO

-- 7) CHECK TENTATIVAS (1..3, regra de PRD: limite de 3 tentativas)
IF OBJECT_ID('dbo.CK_SERASA_PEFIN_BAIXAS_TENTATIVAS', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.SERASA_PEFIN_BAIXAS WITH CHECK
    ADD CONSTRAINT CK_SERASA_PEFIN_BAIXAS_TENTATIVAS
        CHECK (TENTATIVAS BETWEEN 1 AND 3);
END
GO

-- 8) Indice de navegacao por venda + criacao
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_BAIXAS_NUM_VENDA_FK'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_BAIXAS')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_BAIXAS_NUM_VENDA_FK
        ON dbo.SERASA_PEFIN_BAIXAS (NUM_VENDA_FK, DT_CRIACAO DESC)
        INCLUDE (NUMERO_PARCELA, STATUS, CONTRACT_NUMBER, TRANSACTION_ID, MOTIVO);
END
GO

-- 9) Indice unico em TRANSACTION_ID (idempotencia de webhook)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SERASA_PEFIN_BAIXAS_TRANSACTION_ID'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_BAIXAS')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_SERASA_PEFIN_BAIXAS_TRANSACTION_ID
        ON dbo.SERASA_PEFIN_BAIXAS (TRANSACTION_ID)
        WHERE TRANSACTION_ID IS NOT NULL;
END
GO

-- 10) Indice por STATUS + DT_ATUALIZACAO (filas, dashboard)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_SERASA_PEFIN_BAIXAS_STATUS'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_BAIXAS')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERASA_PEFIN_BAIXAS_STATUS
        ON dbo.SERASA_PEFIN_BAIXAS (STATUS, DT_ATUALIZACAO DESC)
        INCLUDE (NUM_VENDA_FK, NUMERO_PARCELA, CONTRACT_NUMBER, MOTIVO, TRANSACTION_ID);
END
GO

-- 11) Indice unico filtrado: impede duplicata ATIVA por parcela
--     Estados ativos: AGUARDANDO_APROVACAO, APROVADA, PENDENTE_ENVIO,
--     BAIXA_ENVIADA, BAIXA_AGUARDANDO_RETORNO.
--     Estados finais (REJEITADA, BAIXADO_SUCESSO, BAIXADO_ERRO, APROVADA_FALHA_ENVIO)
--     NAO bloqueiam novas solicitacoes -- isso permite reabertura via nova solicitacao.
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_SERASA_PEFIN_BAIXAS_ATIVA'
      AND object_id = OBJECT_ID('dbo.SERASA_PEFIN_BAIXAS')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_SERASA_PEFIN_BAIXAS_ATIVA
        ON dbo.SERASA_PEFIN_BAIXAS (
            NUM_VENDA_FK,
            CONTRACT_NUMBER,
            NUMERO_PARCELA
        )
        WHERE STATUS IN (
            'AGUARDANDO_APROVACAO',
            'APROVADA',
            'PENDENTE_ENVIO',
            'BAIXA_ENVIADA',
            'BAIXA_AGUARDANDO_RETORNO'
        );
END
GO
