SET XACT_ABORT ON;
GO

-- Execute este script no banco exclusivo de auditoria (GERENCIAMENTO).
-- A API usa a conexao AuditDb e nunca grava esta tabela no banco operacional.

IF OBJECT_ID(N'dbo.API_TRAFFIC_AUDIT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.API_TRAFFIC_AUDIT
    (
        AUDIT_ID bigint IDENTITY(1,1) NOT NULL,
        ID uniqueidentifier NOT NULL,
        REQUESTED_AT_UTC datetime2(3) NOT NULL,
        HTTP_METHOD varchar(10) NOT NULL,
        ENDPOINT nvarchar(500) NOT NULL,
        RAW_PATH nvarchar(1000) NOT NULL,
        STATUS_CODE int NOT NULL,
        DURATION_MS bigint NOT NULL,
        USER_NAME nvarchar(255) NOT NULL,
        SOURCE_IP varchar(64) NULL,
        API_NAME nvarchar(150) NOT NULL,
        ENVIRONMENT nvarchar(50) NOT NULL,
        SOURCE_SYSTEM nvarchar(150) NULL,
        USER_AGENT nvarchar(1000) NULL,
        TRACE_ID varchar(64) NULL,
        CONSTRAINT PK_API_TRAFFIC_AUDIT PRIMARY KEY CLUSTERED (AUDIT_ID),
        CONSTRAINT UQ_API_TRAFFIC_AUDIT_ID UNIQUE NONCLUSTERED (ID)
    );

    CREATE INDEX IX_API_TRAFFIC_AUDIT_REQUESTED_AT
        ON dbo.API_TRAFFIC_AUDIT (REQUESTED_AT_UTC DESC)
        INCLUDE (STATUS_CODE, DURATION_MS, API_NAME, ENVIRONMENT);

    CREATE INDEX IX_API_TRAFFIC_AUDIT_ENDPOINT
        ON dbo.API_TRAFFIC_AUDIT (ENDPOINT, HTTP_METHOD, REQUESTED_AT_UTC DESC)
        INCLUDE (STATUS_CODE, DURATION_MS, USER_NAME);

    CREATE INDEX IX_API_TRAFFIC_AUDIT_CONSUMER
        ON dbo.API_TRAFFIC_AUDIT (USER_NAME, SOURCE_SYSTEM, REQUESTED_AT_UTC DESC)
        INCLUDE (ENDPOINT, STATUS_CODE, DURATION_MS);
END;
GO
