SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.API_LOAD_TEST_RUN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.API_LOAD_TEST_RUN
    (
        RUN_ID uniqueidentifier NOT NULL PRIMARY KEY,
        PROFILE_KEY nvarchar(50) NOT NULL,
        PROFILE_NAME nvarchar(120) NOT NULL,
        STATUS nvarchar(30) NOT NULL,
        TARGET_BASE_URL nvarchar(500) NOT NULL,
        TRIGGERED_BY nvarchar(255) NOT NULL,
        STARTED_AT_UTC datetime2(3) NOT NULL,
        FINISHED_AT_UTC datetime2(3) NULL,
        EXPECTED_DURATION_SECONDS int NOT NULL,
        TOTAL_REQUESTS bigint NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_TOTAL_REQUESTS DEFAULT 0,
        FAILED_REQUESTS bigint NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_FAILED_REQUESTS DEFAULT 0,
        ERROR_RATE float NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_ERROR_RATE DEFAULT 0,
        AVERAGE_DURATION_MS float NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_AVG_DURATION DEFAULT 0,
        P95_DURATION_MS float NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_P95_DURATION DEFAULT 0,
        P99_DURATION_MS float NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_P99_DURATION DEFAULT 0,
        PEAK_VIRTUAL_USERS int NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_PEAK_VUS DEFAULT 0,
        MAX_REQUESTS_PER_SECOND float NOT NULL CONSTRAINT DF_API_LOAD_TEST_RUN_MAX_RPS DEFAULT 0,
        THRESHOLDS_PASSED bit NULL,
        SUMMARY_JSON nvarchar(max) NULL
    );

    CREATE INDEX IX_API_LOAD_TEST_RUN_STARTED_AT
        ON dbo.API_LOAD_TEST_RUN (STARTED_AT_UTC DESC);
END;
GO

IF OBJECT_ID(N'dbo.API_LOAD_TEST_TIMELINE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.API_LOAD_TEST_TIMELINE
    (
        RUN_ID uniqueidentifier NOT NULL,
        TIMESTAMP_UTC datetime2(3) NOT NULL,
        ELAPSED_SECONDS int NOT NULL,
        REQUESTS bigint NOT NULL,
        FAILURES bigint NOT NULL,
        AVERAGE_DURATION_MS float NOT NULL,
        P95_DURATION_MS float NOT NULL,
        ACTIVE_VIRTUAL_USERS int NOT NULL,
        CONSTRAINT PK_API_LOAD_TEST_TIMELINE PRIMARY KEY (RUN_ID, ELAPSED_SECONDS),
        CONSTRAINT FK_API_LOAD_TEST_TIMELINE_RUN
            FOREIGN KEY (RUN_ID) REFERENCES dbo.API_LOAD_TEST_RUN (RUN_ID) ON DELETE CASCADE
    );
END;
GO

IF OBJECT_ID(N'dbo.API_LOAD_TEST_ENDPOINT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.API_LOAD_TEST_ENDPOINT
    (
        RUN_ID uniqueidentifier NOT NULL,
        NAME nvarchar(600) NOT NULL,
        HTTP_METHOD varchar(10) NOT NULL,
        ENDPOINT nvarchar(500) NOT NULL,
        EXECUTION_MODE varchar(20) NOT NULL,
        REQUESTS bigint NOT NULL,
        FAILURES bigint NOT NULL,
        ERROR_RATE float NOT NULL,
        AVERAGE_DURATION_MS float NOT NULL,
        MINIMUM_DURATION_MS float NOT NULL,
        MAXIMUM_DURATION_MS float NOT NULL,
        P95_DURATION_MS float NOT NULL,
        P99_DURATION_MS float NOT NULL,
        CONSTRAINT PK_API_LOAD_TEST_ENDPOINT PRIMARY KEY (RUN_ID, NAME),
        CONSTRAINT FK_API_LOAD_TEST_ENDPOINT_RUN
            FOREIGN KEY (RUN_ID) REFERENCES dbo.API_LOAD_TEST_RUN (RUN_ID) ON DELETE CASCADE
    );
END;
GO
